/**
 * 动态参数提取工具
 * 从Python策略代码中提取可配置参数，实现参数面板 ↔ 代码的双向绑定
 */

export interface ExtractedParam {
  id: string;
  displayName: string;
  type: 'int' | 'float' | 'enum' | 'bool';
  defaultValue: number | string | boolean;
  range?: { min: number; max: number };
  currentValue: number | string | boolean;
  lineNumbers: { start: number; end: number };
}

/**
 * 从Python代码中提取参数定义
 *
 * 参数标记格式：# @param: <param_id>|<display_name>|<type>|<default_value>|<range>
 *
 * 示例：
 * # @param: ema_period|EMA Period|int|20|5-100
 * self.ema_period = 20
 */
export function extractParamsFromCode(code: string): ExtractedParam[] {
  const params: ExtractedParam[] = [];
  const lines = code.split('\n');

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // 检查是否有 @param 标记
    if (line.includes('# @param:')) {
      const match = line.match(/# @param:\s*(\w+)\|(.+)\|(\w+)\|(.+)\|(.+)/);

      if (match) {
        const [_, id, displayName, type, defaultValue, range] = match;

        // 提取当前值（下一行的赋值语句）
        const nextLine = lines[i + 1];
        let currentValue: any = defaultValue;

        if (nextLine && nextLine.includes('self.')) {
          const valueMatch = nextLine.match(/self\.\w+\s*=\s*(\d+\.?\d*)/);
          if (valueMatch) {
            currentValue = parseFloat(valueMatch[1]);
          } else {
            // 尝试匹配字符串或布尔值
            const strMatch = nextLine.match(/self\.\w+\s*=\s*["'](.+)["']/);
            if (strMatch) {
              currentValue = strMatch[1];
            } else {
              const boolMatch = nextLine.match(/self\.\w+\s*=\s*(True|False)/);
              if (boolMatch) {
                currentValue = boolMatch[1] === 'True';
              }
            }
          }
        }

        // 提取范围
        const rangeMatch = range.match(/(\d+\.?\d*)-(\d+\.?\d*)/);
        const rangeObj = rangeMatch ? {
          min: parseFloat(rangeMatch[1]),
          max: parseFloat(rangeMatch[2])
        } : undefined;

        params.push({
          id,
          displayName,
          type: type as 'int' | 'float',
          defaultValue: type === 'int' || type === 'float' ? parseFloat(defaultValue) : defaultValue,
          range: rangeObj,
          currentValue: currentValue,
          lineNumbers: { start: i, end: i + 1 }
        });
      }
    }
  }

  return params;
}

/**
 * 更新代码中的参数值（双向绑定）
 */
export function updateCodeWithParams(
  code: string,
  params: ExtractedParam[]
): string {
  const lines = code.split('\n');

  params.forEach(param => {
    const { start, end } = param.lineNumbers;

    // 更新赋值语句（在注释行的下一行）
    const assignmentLine = lines[start + 1];
    if (assignmentLine && assignmentLine.includes('self.')) {
      // 替换数值
      const updated = assignmentLine.replace(
        /=\s*\d+\.?\d*/,
        `= ${param.currentValue}`
      );
      lines[start + 1] = updated;
    }
  });

  return lines.join('\n');
}

/**
 * 生成带参数标记的策略代码模板
 */
export function generateStrategyCodeWithParams(
  strategyName: string,
  params: ExtractedParam[]
): string {
  let code = `# ${strategyName} Strategy
# Generated by PaperForge Strategy Agent

import pandas as pd
import numpy as np

class ${strategyName.replace(/\s+/g, '')}Strategy:
    def __init__(self):
`;

  // 添加参数定义
  params.forEach(param => {
    const rangeStr = param.range ? `${param.range.min}-${param.range.max}` : '';
    code += `        # @param: ${param.id}|${param.displayName}|${param.type}|${param.defaultValue}|${rangeStr}\n`;
    code += `        self.${param.id} = ${param.currentValue}\n\n`;
  });

  // 添加策略逻辑
  code += `    def generate_signals(self, df):
        """
        Generate trading signals
        """
        # Strategy logic will be implemented by Strategy Agent
        df['signal'] = 0
        return df

    def risk_management(self, signal, position, current_price):
        """
        Risk management logic
        """
        # Risk logic will be implemented by Risk Agent
        return position
`;

  return code;
}

/**
 * 参数验证
 */
export function validateParamValue(param: ExtractedParam, value: any): boolean {
  if (param.type === 'int' || param.type === 'float') {
    const numValue = parseFloat(value);
    if (isNaN(numValue)) return false;

    if (param.range) {
      return numValue >= param.range.min && numValue <= param.range.max;
    }
    return true;
  }

  return true;
}

/**
 * 测试案例
 */
export function testParamExtraction() {
  const testCode = `
class TestStrategy:
    def __init__(self):
        # @param: ema_period|EMA Period|int|20|5-100
        self.ema_period = 20

        # @param: stop_loss|Stop Loss %|float|5.0|1-20
        self.stop_loss = 5.0
`;

  const params = extractParamsFromCode(testCode);
  console.log('Extracted params:', params);
  // Expected: [
  //   { id: 'ema_period', displayName: 'EMA Period', type: 'int', currentValue: 20, ... },
  //   { id: 'stop_loss', displayName: 'Stop Loss %', type: 'float', currentValue: 5.0, ... }
  // ]

  const updatedParams = [
    { ...params[0], currentValue: 30 },
    { ...params[1], currentValue: 8.0 }
  ];

  const updatedCode = updateCodeWithParams(testCode, updatedParams);
  console.log('Updated code:', updatedCode);
  // Expected: self.ema_period = 30
  //           self.stop_loss = 8.0
}